name: Build
on:
  push:
    branches: [master]
env:
  IMAGE: weters/sqmgr-api
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch origin +refs/tags/*:refs/tags/*

      - name: set version
        run: echo "VERSION=$(git describe --always --dirty)" >> $GITHUB_ENV

      - name: docker log in
        run:  echo ${{ secrets.DOCKER_PASSWORD }} | base64 --decode | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: docker build and tag
        run: |
          docker build --build-arg VERSION=${{ env.VERSION }} -t ${{ env.IMAGE }}:${{ env.VERSION }} .
          docker tag ${{ env.IMAGE }}:${{ env.VERSION}} $IMAGE:latest

      - name: push version
        run: |
          docker push ${{ env.IMAGE }}:${{ env.VERSION }}
          docker push ${{ env.IMAGE }}:latest
