name: Deploy
on:
  workflow_dispatch:
env:
  IMAGE: weters/sqmgr-api
jobs:
  deploy:
    name: 'Deploy to Production'
    runs-on: ubuntu-latest
    steps:
      - name: 'deployment pending'
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'pending'
          token: '${{ github.token }}'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git fetch origin +refs/tags/*:refs/tags/*

      - name: set version
        run: echo "VERSION=$(git describe --always --dirty)" >> $GITHUB_ENV

      - name: set image
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deploy sqmgr-api sqmgr=${{ env.IMAGE }}:${{ env.VERSION }} --record

      - name: rollout status
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deploy sqmgr-api

      - name: 'deployment success'
        if: success()
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'success'
          token: '${{ github.token }}'

      - name: 'deployment failure'
        if: failure()
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'failure'
          token: '${{ github.token }}'
