name: Deploy
on: [deployment]
env:
  IMAGE: weters/sqmgr-api
jobs:
  build:
    name: 'Deploy to Production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git fetch origin +refs/tags/*:refs/tags/*

      - name: set version
        run: echo "::set-env name=VERSION::$(git describe --always --dirty)"

      - name: set image
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deploy sqmgr-api sqmgr=${{ env.IMAGE }}:${{ env.VERSION }} --record

      - name: rollout status
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deploy sqmgr-api
