name: Test
on:
  pull_request:
    branches: [master]
jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432/tcp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - run: go mod download
      - run: go build -o migrate -tags postgres github.com/golang-migrate/migrate/v4/cmd/migrate
      - run: go build -o golint golang.org/x/lint/golint
      - run: ./migrate -path ./sql -database postgres://postgres:@localhost:${{ job.services.postgres.ports['5432'] }}/postgres?sslmode=disable up
      - run: |
          ./golint -set_exit_status ./...
          ./hack/gofmt-check.sh
          go vet ./...
      - run: SQMGR_CONF_DSN="user=postgres port=${{ job.services.postgres.ports['5432'] }} sslmode=disable" INTEGRATION=1 go test -coverprofile=coverage.out ./...
