name: Test
on:
  push:
    branches-ignore: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432/tcp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.12'
      - run: |
          go mod download
          go install -tags postgres github.com/golang-migrate/migrate/v4/cmd/migrate
          migrate -path ./sql -source postgres://postgres:@localhost:5432?/postgres?sslmode=disable up
          golint -set_exit_status ./...
          ./hack/gofmt-check.sh
          go vet ./...
          INTEGRATION=1 go test -coverprofile=coverage.out ./...
